
image:
  file: Dockerfile
vscode:
  extensions:
    - jebbs.plantuml
tasks:
  - init: |
      unzip -d /tmp/ext ./extensions/shd101wyy.markdown-preview-enhanced-0.6.3.vsix
      mv /tmp/ext/extension /workspace/.vscode-remote/extensions/shd101wyy.markdown-preview-enhanced-0.6.3
