version: "3.7"
services:
  ubuntu:
    image: ghcr.io/u032582/ubuntu-devuser:latest
    build:
      context: .
      args:
        - UID=${USERID:-1001}
        - GID=${GID:-1001}
    environment:
      - DISPLAY=${DISPLAY}
      - USERID=${USERID:-1001}
      - GID=${GID:-1001}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
